<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE texts [
    <!ELEMENT texts (text+)>
    <!ELEMENT text (#PCDATA)>
    <!ATTLIST text name CDATA #REQUIRED>
]>
<!--
    Document   : sk.xml
    Created on : 10. duben 2011, 17:07
    Author     : Maros Kucbel
    Description:
        Localized text for mathml2text.xsl stylesheet.
-->

<texts>
    <text name="subtract">mínus</text>
    <text name="add">plus</text>
    <text name="multiply">krát</text>
    <text name="divide">deleno</text>
    <text name="equals">sa rovná</text>
    <text name="logarithm_base">logaritmus so základom</text>
    <text name="logarithm_from">z</text>
    <text name="natural_logarithm">prirodzený logaritmus z</text>
    <text name="open_braces">otvoriť zátvorku</text>
    <text name="close_braces">uzavrieť zátvorku</text>
    <text name="fraction">zlomok</text>
    <text name="divided_by">lomeno</text>
    <text name="binomial_coefficient">kombinačné číslo</text>
    <text name="choose">nad</text>
    <text name="square_root">druhá odmocnina z</text>
    <text name="superscript">umocnené na</text>
    <text name="root">odmocnina z</text>
    <text name="root_suffix">-tá</text>
    <text name="sine">sínus</text>
    <text name="cosine">kosínus</text>
    <text name="tangent">tangens</text>
    <text name="cotangent">kotangens</text>
    <text name="lim">limita</text>
    <text name="as">keď sa</text>
    <text name="approaches">blíži k</text>
    <text name="integral">integrál</text>
    <text name="definite">určitý</text>
    <text name="dee">dé</text>
    <text name="from">od</text>
    <text name="to">do</text>
    <text name="of">z</text>
    <text name="alpha">alfa</text>
    <text name="beta">beta</text>
    <text name="gamma">gama</text>
    <text name="delta">delta</text>
    <text name="epsilon">epsilon</text>
    <text name="zeta">zéta</text>
    <text name="eta">éta</text>
    <text name="theta">théta</text>
    <text name="iota">jota</text>
    <text name="kappa">kapa</text>
    <text name="lambda">lambda</text>
    <text name="mu">mí</text>
    <text name="nu">ní</text>
    <text name="xi">ksí</text>
    <text name="omicron">omikron</text>
    <text name="pi">pí</text>
    <text name="rho">ró</text>
    <text name="sigma">sigma</text>
    <text name="tau">tau</text>
    <text name="upsilon">ypsilon</text>
    <text name="phi">fí</text>
    <text name="chi">chí</text>
    <text name="psi">psí</text>
    <text name="omega">omega</text>
    <text name="squared">na druhú</text>
    <text name="sum">suma</text>
    <text name="lt">je menšie ako</text>
    <text name="gt">je väčšie ako</text>
    <text name="leq">je menšie alebo rovné</text>
    <text name="geq">je väčšie alebo rovné</text>
</texts>